### ISSUE TITLE
UAT Feedback/to-do list

### ISSUE THREAD

**Issue by andrjohns** [AUS-DOH-Safety-and-Quality/PowerBI-Funnels#91]
- [ ] After adding an X axis limit it does not hide values/limits when they move behind the y axis
- [ ] When adding an X axis limit the work around for the SPC Y axis limit question does not work, it forces a default value and is no longer dynamic.
- [ ] Requires multiplier to be 100 to display percentage tooltip correctly for proportion
- [ ] Funnel Text errors out when a tooltip measure has a value of 'Null'
- [ ] Funnel plot effectively gets all it's fields re-arranged when importing the new funnel plot. This will affect all custom visuals that currently host the previous version of the custom visual.
- [ ] Unused conditional formatting fields inherit random field values (but no issue as they are currently not enabled)
- [ ] Target(s) line changed from Solid to Dashed automatically
- [ ] Can't remove additional target value once implemented (Only work around is to click back, hoping that PBI will let you)
- [ ] I still don't understand what maximum ticks does
